# Site settings
author: Asha Fernandez
title: # Logic and Conditionals a metaphor for life
header-img: img/home-bg.png
email: ash.fernan90@gmail.com
copyright_name: Asha Fernandez
description: > # this means to ignore newlines until "baseurl:"
  Logic and Conditionals
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  AshFernan

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
